### ISSUE TITLE
User story: 1/2 View navigation - ZoomOut, and loading custom month/year elements

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#49]
### Prereqs:
- [x] Team3 finished template work for monthly and yearly objects

### Work flow:
1. Zoom-out button has a `zoom-out` callback onClick that handles:
  - saving state to history
  - deciding the appropriate `transition` function to call

2. `transitionDaily/Monthly/Yearly` will:
  - toggle displays as necessary to hide/show the correct content (divs for Day, Month, Year)
  - call the appropriate `load` function

3. `loadDay/Month/Year` will:
  - generate an ID (`IDConverter.generateID`) using `currDate` if not provided with an ID
  - create the appropriate object (using `daily-log.js`, `monthly-log.js`, or `yearly-log.js`) with `document.createElement`
  - attempt to fetch data from database with ID
    - calls the objects `data`- setter function with either [ID, data]
    - result from database used if succesful, otherwise `{}`
- replace the old element under `internal-content`
  - divs for Day/Month/Year is `.remove()`d
  - div is set to new object instead
  - new div is `append`ed 

### Tasks:
- [x] create `loadMonth` and `loadYear` functions
- [x] Figure out the rest of the tasks
