### ISSUE TITLE
User story: 2/2 View Navigation - Calendar (Zoom-In)

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#50]
### Prereqs
- [x] Team 3 already setup basic HTML skeleton code for the calendar
  - IDs of the calendar entries ARE the IDs used to load/store that day/month obj to DB
- [ ] Frontend team might want to start working on styling, could be a bit of hassle later

### Workflow
1. Each button in the calendar has listens for User click
2. OnClick, passes the event into a callback to handle the "zoom-in" to the target Date/Month
3. `zoomIn` will:
- Check where to transition to (based off current view)
- Call the appropriate `transition` function (which handles toggling displays on/off)
- Call the appropriate `load` function (which handles creation of day/month custom element, setting data, appending/replacingChild)

### Tasks
- [x] Make this issue
  - [x] Fulfill Prereqs
  - [x] Hammer down the Workflow (helpful to plan and might be useful when writing documentation)
  - [x] Figure out how to break down feature into tasks
- [x] Write the `zoomIn` function
