### ISSUE TITLE
User Story: Bullet Types

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#52]
### Prereqs
- [x] Requested a visual aide for the various types of bullets from Team2
- [x] Bullet custom element is set up with a `type` item in it's `data`
- [x] Confirm with the group what exactly is our approach to changing the bullet types
  - ~~Radial menu, right-click/left-click toggling through, drop down, etc.~~
  - Edit: confirmed that we have a context menu on right click (courtesy of Team 2)
    - context menu contains options for: task, note, event, migrated, irrelevant
  
### Workflow
1. User right-clicks on bullet-point and context menu appears
2. User can click on any of the options to update the bullet type
3. If the bullet type gets updated, the displayed icon changes accordingly and the json data object gets updated
3. User can click anywhere on the window to close the context menu

### Tasks
- [x] understand how the context menu works and the structure of the html elements in it
- [x] add click event listener to each option in the context menu when it opens
  - [x] event listener should check if the new bullet type is different from the current bullet type (if they are the same, nothing has to be updated)
  - [x] if the bullet type is different, change the icon displayed for that bullet and update its type in the object in storage
  - [x] if the bullet type is selected as strikethrough, add the appropriate class to the bullet text for strikethrough styling
- [x] add a statement to the bullet's set data function to display the appropriate bullet icon when the bullet is being created from storage
