### ISSUE TITLE
User story: Trackers

### ISSUE THREAD

**Issue by praneetbhoj** [cse110-sp21-group10/cse110-sp21-group10#54]
### Prereqs
- [x] Already have the daily and monthly log elements from our previous work

### Workflow
1. User opens daily log and can interact with the trackers
  - mood and sleep quality trackers are presented as sliders
  - calorie intake and spending trackers are presented as number inputs
  - exercise tracker is presented as a checkbox
  - need to add event listener to each of the trackers
    - when the value of the tracker is changed, the event listener will update the JSON object locally and store it
2. When the user switches to monthly view...
  - monthly log object loops through each of the days and get their tracker data
  - tracker data will be put into an array that will be used to graph the data
    - graphing data using Chart.js

### Tasks
- [x] Plan out flow of how the trackers will be presented and how their data will be collected for charting
- [x] Create the various elements for the trackers on the daily view
  - [x] sliders for mood and sleep quality; input boxes for calorie intake and spending
- [x] Add event listeners to the tracker elements so that JSON data can be updated when tracker values are changed
- [x] Loop through the daily logs and fetch their tracker data in the monthly log object
  - [x] Consolidate the tracker data into arrays in the monthly log so they can be plotted
  - [x] Graph the tracker data using Chart.js
