### ISSUE TITLE
User story: Labels

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#56]
### Workflow
- User hovers over bullet to display the "empty" label button
  - mostly html template + css work
  - empty bullet is hallow with black outline
- User clicks to open up a context menu to choose between the 5 options
  - finance, fitness, academic, household, work, and leisure
  - solid bullets with associated color
- Applies the label to the bullet
  - FA's 'bookmark' icon is appended to the top of a stack of labels, will look something like:
![image](https://user-images.githubusercontent.com/56041333/120731057-a60e6880-c497-11eb-9ad4-8a1a180dab0b.png)
  - clickListener added to allow for removal by clicking on that label
    - CSS will layer an ❌ over the label on hover to indicate that clicking will remove
  - customary update local data and database afterwards

### Tasks
- [x] Write this Issue :)
  - [ ] Request prereqs from other Teams
  - [x] Decide on a workflow (helpful in planning and can be re-used in documentation)
  - [x] Write Tasks to subdivide big features into manageable parts (for organization)
- [x] Write a contextMenu in `log.html` to refer to later
- [x] Create a hard-coded (for now) `labels` variable in `script.js` used
- [x] Write helper functions for handling labels in `bullet.js`
  - [x] `setLabels` - for existing labels (iterates through data and calls `createLable`)
  - [x] `createLabel` - for both new and existing labels with given data --> only to display. Also handles triggers for removal(click Listener)
  - [x] `removeLabel` - removes label from display, parent data, and database
- [x] Add a click listener to options in label's context menu
  - [x] save to parent data and database, call on `createLabel` to handle display
- [ ] Add CSS layering of an ❌ on hover
