### ISSUE TITLE
User story: Personalization - Data Persistance

### ISSUE THREAD

**Issue by maniacalhamster** [cse110-sp21-group10/cse110-sp21-group10#57]
### Prereqs
- [x] `index.js` interface for user selection of font/theme

### Workflow
1. `style` variable `export`ed, will hold
  a. `fontType` - Defaults to "Time new Roman"
  b. `themeType` - Defaults to ""
2. `Database.store` called whenever user selects a font/theme
  a. `style.fontType`/`style.themeType` updates with a click Listener on each font/theme choice
  b. `style` pushed to database under the ID `'S'` (singular ID, just gets reused)
3. `loadStyle()` helper function `export`ed will
  a. set the the display using values in `style` (not entirely sure what Asya did, just moved her code here lol)
4. `setupScript()` helper function defined in `script.js` that will now also:
  a. call `Databas.fetch` with the `'S'` ID and on success:
    i. `import`ed `style`'s `fontType` and `themeType` updated (handles data)
    ii. `import`ed `loadStyle()` helper function gets called (handle display)
  b. Is called after every 

### Tasks
- [x] Write this Issue :)
  - [x] Request prereqs from other Teams
  - [x] Decide on a workflow (helpful in planning and can be re-used in documentation)
  - [x] Write Tasks to subdivide big features into manageable parts (for organization)
- [x] Write `loadStyle()`
- [x] Update `setupScript()`
