### ISSUE TITLE
User story: Section Reordering

### ISSUE THREAD

**Issue by praneetbhoj** [cse110-sp21-group10/cse110-sp21-group10#78]
### Prereqs
- [x] Already have the rest of the daily log object

### Tasks
- [x] when the daily log object is being constructed...
  - [x] check if we are constructing the daily notes section
  - [x] if we aren't, just append the new section to the bottom of the daily log
  - [x] if we are constructing the daily notes, get the current top section of the log and append the daily notes section above it
